version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
